language: cpp
os: linux
compiler:
    - clang
    - gcc

git:
    depth: 1

tags: true

sudo: true

script:
    - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=install
    - cmake --build _build/
    - cd _build/
    - cpack --config CPackSourceConfig.cmake
    - cd ..

addons:
    apt:
        - cmake
        - cmake-data
        - rpm

deploy:
    provider: releases
    api_key: ${GITHUB_KEY}
    file_glob: true
    file:
        - "install/packages/*.deb"
        - "install/packages/*.rpm"
        - "install/packages/*.dmg"
        - "install/packages/*.tar.gz"
        - "install/packages/*.zip"
    skip_cleanup: true
    on:
        tags: true
