language: cpp
os: linux
compiler:
    - clang
    - gcc

script:
    - cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=install
    - cmake --build build/
    - cmake --build build/ --target install

addons:
    apt:
        - cmake
        - cmake-data
